# Generated by Django 5.2 on 2025-05-14 01:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="persondirector",
            new_name="movies_pers_movie_i_957f84_idx",
            old_fields=("movie", "order"),
        ),
    ]
