name: tests

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
        django-version: ['4.2', '5.0', '5.1', '5.2']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache installed requirements
      uses: actions/cache@v4
      with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v01
    - name: Install tox-gh-actions and coveralls
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions coveralls
    - name: Run tests with tox
      env:
        OS: ${{ matrix.os }}
        DJANGO: ${{ matrix.django-version }}
      run: tox
    - name: Run tests for example
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10' && matrix.django-version == '4.2' }}
      run: |
        python -m pip install .[test,example]
        python -m pytest example
    - name: Generate coverage.xml
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10' && matrix.django-version == '4.2' }}
      uses: actions/upload-artifact@v4
      with:
        name: tox-gh-actions-coverage
        path: coverage.xml
        if-no-files-found: error
    - name: Upload coverage.xml to Coveralls
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10' && matrix.django-version == '4.2' }}
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
